### ISSUE TITLE
Chrome v50 activates drop down twice (flickering)

### ISSUE THREAD

**Issue by cibgraphics** [AudithSoftworks/Uniform#424] opened 2016-06-10 18:39 UTC
This seems to happen after updating to Chrome 50 (though not sure if it is 100% related).  You can see what is happening here:

http://screencast.com/t/gbL9O6siz3f

I am running v.2.2.2 of the plugin on Chrome 50 on OSX. (I don't think it is happening on Windows).

commenting out 

```
var selHtml = $el.find(":selected").html();
```

Seems to fix the issue (not sure why) or perhaps breaks something else that I am not seeing.

**Comment by shehi** [comment] 2016-06-12 08:01
Having some JSFiddle or similar would help a lot. Our code is available in CDNjs as well, so you could use the library externally from that source.

**Comment by merauluka** [comment] 2016-06-14 16:31
This was also happening to me on my Macbook Pro running Chrome v.50. When I checked my version number, an update was available. After restarting Chrome with the updated applied, the flickering has ceased.

**Comment by shehi** [comment] 2016-06-15 07:54
Since Chrome auto-updates in most platforms and this issue is version-bound, I will mark it as Low Priority.

**Comment by cibgraphics** [comment] 2016-06-15 17:45
It happens to me after Chrome updated... v51.

**Comment by shehi** [comment] 2016-06-16 07:52
@cibgraphics : I am afraid, I can't do anything (at least right now, due to lack of time) unless you demonstrate the issue with some JSFiddle. Also it'd be nice if you guys consider the fact that, this being a Client side library, reproducing many circumstances in which these bugs occur is quite hard, if not impossible. That's why it's paramount you showcase your issues to us for quicker detection, classification and solution.

**Comment by nysa** [comment] 2016-06-20 15:53
Here's a JSFiddle demonstrating the bug:
https://jsfiddle.net/o2mmhata/

The bug occurs on Chrome v50 and v51 on Mac OS X 10.11.5 (I haven't checked other operating systems) when used with jQuery v1.4.3 up to and including v1.11.3.

The JSFiddle above is using jQuery v1.11.3 and Uniform v2.2.2.

**Comment by fidian** [comment] 2016-06-20 16:11
Does not show up on 51.0.2704.63 (Official Build) (64-bit) running on Ubuntu 15.10.  It is possible that the issue is there, but is animated so quickly that it is impossible to notice.  When performing step-through debugging, I don't see it.

**Comment by merauluka** [comment] 2016-06-20 16:14
I'm using 51.0.2704.84 (64-bit) on OSX 10.10.5. No issues after upgrading
to this version of Chrome. Though I did see it in version 50 of Chrome
prior to updating (which lead me to this case).

**Comment by shehi** [comment] 2016-06-20 18:18
@fidian , I invited you to our SauceLabs team (email should be arriving to your inbox by now). If you find free time, could you please perform a Live debugging on that JSFiddle, using Chrome 50 on latest available MacOS there? I did few tests myself but unfortunately I couldn't detect any flickering. I will investigate this issue further this weekend to get to the bottom of it.

**Comment by shehi** [comment] 2016-06-20 18:36
And what @cibgraphics described in his original demonstration video, I can't reproduce using SauceLabs. Maybe it's too quick and SauceLabs videos are low-framerate. Videos are here:

https://saucelabs.com/beta/manual/test_proxy/7c4dd38f47524fb38c5e06ddeccb4774
https://saucelabs.com/beta/manual/test_proxy/2d075c84b6454a0494214ae2899bc2d4

Both tests are Chrome 50; the first one on MacOS 10, the other MacOS 9.

**Comment by shehi** [comment] 2016-06-20 18:47
Ok, I think this problem is a Chrome 50 bug:

https://github.com/twbs/bootstrap/issues/19865

**Comment by shehi** [comment] 2016-06-20 18:54
I will be closing this issue, assuming it was a browser bug, as all the research in the web indicates it. There are Chrome bug reports in linked Bootstrap issue, and a problem similar to @cibgraphics 's video is depicted in multiple reporter videos.

@fidian , guess there is no need to investigate this further. Feel free to accept my invitations though. :)

**Closed by shehi** 2016-06-20 18:54 UTC
Labels: Browser Bug
