### ISSUE TITLE
Form submitting twice - Only on iPad

### ISSUE THREAD

**Issue by ivyowl** [AudithSoftworks/Uniform#347] opened 2013-07-17 08:27 UTC
Many thanks in advance for any help on this matter.

I have created the HTML for a site which is now being put together by a Database developer. The problem is relating to a registration form.

When a user on a Desktop registers 1 user is created.

When a user on a iPad registers 2 dubplicates are created.

There is logic in place to check if an email address is in the database already, but it seems to happen too quickly to prevent the error.

Also when the calling of uniform is removed the problem also is removed.

This is what i'm using to call uniform:

<script type="text/javascript">
    $(document).ready(function () {
        $("select, input").uniform();
        $(".submit").hide();
    });
</script>

Any advice would be much appreciated.

**Comment by shehi** [comment] 2016-08-24 11:51
This is duplicate of #328 anyway. Closing this one.

**Closed by shehi** 2016-08-24 11:51 UTC
